# Generated by Django 4.1.3 on 2022-12-07 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cars_data',
        ),
    ]
