# Generated by Django 4.1.3 on 2022-12-07 10:30

import cars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0002_delete_cars_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_data',
            fields=[
                ('bus_num', models.AutoField(primary_key=True, serialize=False)),
                ('bus_Name', models.CharField(max_length=100)),
                ('bus_Model', models.CharField(max_length=100)),
                ('bus_route', models.CharField(max_length=100)),
                ('ticket_Price', models.IntegerField(max_length=15)),
                ('bus_Photo', models.FileField(null=True, upload_to=cars.models.user_directory_path, verbose_name='')),
            ],
            options={
                'db_table': 'buses',
            },
        ),
    ]
