# Generated by Django 4.1.3 on 2022-12-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pax_name', models.CharField(max_length=100)),
                ('pax_gender', models.CharField(max_length=100)),
                ('contact_num', models.IntegerField()),
                ('mail', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('total_pax', models.IntegerField()),
            ],
            options={
                'db_table': 'pax_details',
            },
        ),
    ]
