# Generated by Django 4.1.3 on 2022-12-07 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_paxdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paxdetails',
            name='date',
        ),
    ]
