# Generated by Django 4.1.3 on 2022-12-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_paxdetails_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paxdetails',
            name='total_pax',
        ),
    ]
